:lang: no
:attr_orig_language: no
:attr_translation_status: incomplete
:revdate: 2018-08-06
:doctitle_en: How to get started wit GitHub and content production
:doctitle_no: Praktiske tips for å komme igang med GitHub og innholdsproduksjon
:keywords_no: dokumentasjon, GitHub, innholdsproduksjon
:keywords_en: documentation, GitHub, content production
include::./felles/includes/standardheader.adoc[]
include::./felles/includes/commonlinks1.adoc[]


== Etabler lokal filmappe for kloning av github-filer

Lag en filmappe som hjemmeområde for å arbeide lokalt med github-filer.

NOTE: Om du bruker lange navn og dyp mappestruktur i Windows, kan du få problemer med en begrensning på 260
karakterer i total lengde på filnavn. I og med Windows 10 kan denne begrensningen oppheves. Se f.eks.
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ for en oppskrift på
hvordan dette kan gjøres. +
 +
Kort fortalt: På Windows 10 Enterprise kan du kjøre gpedit.msc og endre Aktiver lange Win32 baner under
Datamaskinkonfigurasjon, Administrative maler, System, Filsystem. Du må restarte eller logge av og på for at endringen skal tre i kraft. +
 +
#Overse denne merknaden inntil videre - det er kanskje ikke et problem i praksis. Tips vil flyttes til annet sted...#


== Installer GitHub Desktop
GitHub Desktop anbefales for å klone og oppdatere GitHub-biblioteker.

#Tips om nedlasting og bruk kommer her#


NOTE: GitHub desktop kan av og til ha problemer med å aksessere .gitconfig-filen. Dette kan trolig fikses ved å opprette en systemvariabel HOME til den mappen du har opprettet som
hjemmeområde for dine lokale GitHub-filer (bruk Kontrollpanel, System, Avanserte systeminnstillinger, miljøvariabler). +
 +
Tips: Det er kanskje en god ide å unngå å bruke nettverks-drive (som noen virksomheter bruker som default for Dokumenter)? Bruk kanskje heller en katalog direkte under ditt brukernavn på C:\Users? Se også  https://github.com/desktop/desktop/issues/4119.


== Installer redigeringsverktøy
Flere verktøy for editering av asciidoc finnes. De fleste vil ha nytte av en editor som gir støtte til formatering og viser resultatet direkte (WYSIWIG). Anbefalt her:

. AsciidocFX. #Mer info kommer.#
. Atom...  #Mer info kommer.#
. stackedit.io


== Klon GitHub-prosjektet til din maskin

Med Github desktop: File | Clone a repository

#Mer info kommer.#

== Start å skrive
Du kan gjøre det helt enkelt eller så avansert du måtte ønske, eller noe midt i mellom. Her er noen tips:

* link:Tips_for_å_skrive_artikler_eller_kapitler.adoc[Tips for å skrive enkle artikler eller kapitler]
* link:Tips_for_å_skrive_dokumenter_eller_bøker.adoc[Tips for å skrive dokumenter eller bøker]
* Avanserte tips for innholdsproduksjon (#kommer#)

== Andre tips
#Flere tips kommer her;)#



